import java.awt.Image;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Brayan Taday
 */
public class Parqueadero_Ups extends javax.swing.JFrame {

    public static boolean[] disponible = new boolean[45];
    static ArrayList<vehiculo> vehiculos = new ArrayList<>();
    /**
     * Creates new form Parqueadero
     */
    public Parqueadero_Ups() {
        initComponents();
        DateTimeFormatter formateadorDia = DateTimeFormatter.ofPattern("E d MMMM yyyy");
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(500);
                        lblHora.setText(formateador.format(LocalDateTime.now()));
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();
        lblDia.setText(formateadorDia.format(LocalDateTime.now()));
        setLocationRelativeTo(null);
        setResizable(false);
        cargarDatos();
        lblFondo.setIcon(escala("/imagenes/blanco.jpg", lblFondo.getWidth(), lblFondo.getHeight()));
        lblFondoImagen.setIcon(escala("/imagenes/negro.jpg", lblFondoImagen.getWidth(), lblFondoImagen.getHeight()));
        labelImagen.setIcon(escala("/imagenes/parqueadero vector.jpg", labelImagen.getWidth(), labelImagen.getHeight()));
        
    }
    
    public void cargarDatos(){
        int cantCapacidad = disponible.length ;
        int cantOcupados = 0;
        for (int i = 0; i < disponible.length; i++) {
            if(!disponible[i]){
                cantOcupados+=1;
            }
        }
        int cantDisponibles = 45-cantOcupados;
        lblCapacidad.setText(""+cantCapacidad);
        lblOcupados.setText(""+cantOcupados);
        lblDisponibles.setText(""+cantDisponibles);
    }
    
    public Icon escala(String s, int ancho, int altura){
        ImageIcon icono = new ImageIcon(getClass().getResource(s));
        Image imagen = icono.getImage();
        Image imagen2 = imagen.getScaledInstance(ancho, altura, java.awt.Image.SCALE_SMOOTH);
        ImageIcon nuevoicono = new ImageIcon(imagen2);
        return(nuevoicono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtplaca = new javax.swing.JTextField();
        BtnSalir = new javax.swing.JButton();
        BtnIngresar = new javax.swing.JButton();
        btnparqueadero = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblCapacidad = new javax.swing.JLabel();
        lblOcupados = new javax.swing.JLabel();
        lblDisponibles = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();
        lblFondoImagen = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(238, 238, 238));
        label1.setText("Parqueadero UPS");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 320, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ingresar auto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 130, 50));
        getContentPane().add(txtplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 150, 30));

        BtnSalir.setBackground(new java.awt.Color(255, 105, 105));
        BtnSalir.setText("Sacar auto");
        BtnSalir.setActionCommand("");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 120, 30));

        BtnIngresar.setBackground(new java.awt.Color(105, 105, 255));
        BtnIngresar.setText("Ingresar auto");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 120, 30));

        btnparqueadero.setBackground(new java.awt.Color(0, 204, 102));
        btnparqueadero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnparqueadero.setText("Ver parqueadero");
        btnparqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparqueaderoActionPerformed(evt);
            }
        });
        getContentPane().add(btnparqueadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 180, 40));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 720, 20));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 30, 430));

        lblCapacidad.setBackground(new java.awt.Color(0, 0, 0));
        lblCapacidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCapacidad.setText("0");
        lblCapacidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 90, 100, 30));

        lblOcupados.setBackground(new java.awt.Color(0, 0, 0));
        lblOcupados.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOcupados.setText("0");
        lblOcupados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblOcupados, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 100, 30));

        lblDisponibles.setBackground(new java.awt.Color(0, 0, 0));
        lblDisponibles.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDisponibles.setText("0");
        lblDisponibles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("PLACA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        lblDia.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N
        getContentPane().add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 530, 40));

        lblHora.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 36)); // NOI18N
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 150, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Retirar auto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 130, 50));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Disponibles");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("Capacidad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("Ocupados");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, -1));
        getContentPane().add(labelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 310, 340));

        lblFondoImagen.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lblFondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 510));

        lblFondo.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        new Camara().setVisible(true);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        String placa=txtplaca.getText();
        String val = "[A-Z]{3}[-][0-9]{3,4}";
        if(txtplaca.getText().matches(val)){
            if (revisar()){
                JOptionPane.showMessageDialog(null, "Placa ya esta ingresada");
            }else{
//                IngresarVehiculo();
                new Parqueadero(placa).setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Placa incorrecta");
        }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void btnparqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparqueaderoActionPerformed
        new Ventanas().setVisible(true);
    }//GEN-LAST:event_btnparqueaderoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        cargarDatos();
    }//GEN-LAST:event_formWindowActivated

    public boolean revisar(){
        boolean boo=false;
        for(vehiculo obj : vehiculos){
            if(txtplaca.getText().equals(obj.getPlaca())){
                boo=true;
            }
        }return boo;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        for (int i = 0; i < 45; i++) {
            disponible[i]=true;
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parqueadero_Ups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parqueadero_Ups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parqueadero_Ups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parqueadero_Ups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parqueadero_Ups().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton btnparqueadero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblDisponibles;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFondoImagen;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblOcupados;
    private javax.swing.JTextField txtplaca;
    // End of variables declaration//GEN-END:variables

}
