
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brayan Taday
 */
public class Ventanas extends javax.swing.JFrame {

    Parqueadero_Ups obj = new Parqueadero_Ups();
    DefaultTableModel TablaDisponible;
    DefaultTableModel TablaHistorial;
    /**
     * Creates new form Ventanas
     */
    public Ventanas() {
        String[] celdas = {"Puesto","Placa"};
        TablaDisponible = new DefaultTableModel(celdas, 0);
        String[] celdas2 = {"Placa","Fecha","Ingreso","Salida"};
        TablaHistorial = new DefaultTableModel(celdas2, 0);
        initComponents();
        setLocationRelativeTo(null);
        fondoparqueo.setIcon(escala("/imagenes/fondoparqueadero.jpg ", fondoparqueo.getWidth(), fondoparqueo.getHeight()));
        estadio.setIcon(escala("/imagenes/estadio.jpg ", estadio.getWidth(), estadio.getHeight()));
        parqueo1.setBackground(ColoresBotones(0));
        parqueo2.setBackground(ColoresBotones(1));
        parqueo3.setBackground(ColoresBotones(2));
        parqueo4.setBackground(ColoresBotones(3));
        parqueo5.setBackground(ColoresBotones(4));
        parqueo6.setBackground(ColoresBotones(5));
        parqueo7.setBackground(ColoresBotones(6));
        parqueo8.setBackground(ColoresBotones(7));
        parqueo9.setBackground(ColoresBotones(8));
        parqueo10.setBackground(ColoresBotones(9));
        parqueo11.setBackground(ColoresBotones(10));
        parqueo12.setBackground(ColoresBotones(11));
        parqueo13.setBackground(ColoresBotones(12));
        parqueo14.setBackground(ColoresBotones(13));
        parqueo15.setBackground(ColoresBotones(14));
        parqueo16.setBackground(ColoresBotones(15));
        parqueo17.setBackground(ColoresBotones(16));
        parqueo18.setBackground(ColoresBotones(17));
        parqueo19.setBackground(ColoresBotones(18));
        parqueo20.setBackground(ColoresBotones(19));
        parqueo21.setBackground(ColoresBotones(20));
        parqueo22.setBackground(ColoresBotones(21));
        parqueo23.setBackground(ColoresBotones(22));
        parqueo24.setBackground(ColoresBotones(23));
        parqueo25.setBackground(ColoresBotones(24));
        parqueo26.setBackground(ColoresBotones(25));
        parqueo27.setBackground(ColoresBotones(26));
        parqueo28.setBackground(ColoresBotones(27));
        parqueo29.setBackground(ColoresBotones(28));
        parqueo30.setBackground(ColoresBotones(29));
        parqueo31.setBackground(ColoresBotones(30));
        parqueo32.setBackground(ColoresBotones(31));
        parqueo33.setBackground(ColoresBotones(32));
        parqueo34.setBackground(ColoresBotones(33));
        parqueo35.setBackground(ColoresBotones(34));
        parqueo36.setBackground(ColoresBotones(35));
        parqueo37.setBackground(ColoresBotones(36));
        parqueo38.setBackground(ColoresBotones(37));
        parqueo39.setBackground(ColoresBotones(38));
        parqueo40.setBackground(ColoresBotones(39));
        parqueo41.setBackground(ColoresBotones(40));
        parqueo42.setBackground(ColoresBotones(41));
        parqueo43.setBackground(ColoresBotones(42));
        parqueo44.setBackground(ColoresBotones(43));
        parqueo45.setBackground(ColoresBotones(44));
    }

    public Color ColoresBotones(int n){
            if(obj.disponible[n]){
                return Color.GREEN;
            }else{
                return Color.RED;
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        parqueo1 = new javax.swing.JLabel();
        parqueo4 = new javax.swing.JLabel();
        parqueo5 = new javax.swing.JLabel();
        parqueo6 = new javax.swing.JLabel();
        parqueo7 = new javax.swing.JLabel();
        parqueo8 = new javax.swing.JLabel();
        parqueo9 = new javax.swing.JLabel();
        parqueo10 = new javax.swing.JLabel();
        parqueo11 = new javax.swing.JLabel();
        parqueo12 = new javax.swing.JLabel();
        parqueo13 = new javax.swing.JLabel();
        parqueo14 = new javax.swing.JLabel();
        parqueo15 = new javax.swing.JLabel();
        parqueo16 = new javax.swing.JLabel();
        parqueo17 = new javax.swing.JLabel();
        btnvolver = new javax.swing.JButton();
        parqueo19 = new javax.swing.JLabel();
        parqueo20 = new javax.swing.JLabel();
        parqueo21 = new javax.swing.JLabel();
        parqueo22 = new javax.swing.JLabel();
        parqueo23 = new javax.swing.JLabel();
        parqueo24 = new javax.swing.JLabel();
        parqueo25 = new javax.swing.JLabel();
        parqueo45 = new javax.swing.JLabel();
        parqueo44 = new javax.swing.JLabel();
        parqueo43 = new javax.swing.JLabel();
        parqueo42 = new javax.swing.JLabel();
        parqueo41 = new javax.swing.JLabel();
        parqueo36 = new javax.swing.JLabel();
        parqueo37 = new javax.swing.JLabel();
        parqueo38 = new javax.swing.JLabel();
        parqueo39 = new javax.swing.JLabel();
        parqueo40 = new javax.swing.JLabel();
        parqueo35 = new javax.swing.JLabel();
        parqueo34 = new javax.swing.JLabel();
        parqueo33 = new javax.swing.JLabel();
        parqueo32 = new javax.swing.JLabel();
        parqueo31 = new javax.swing.JLabel();
        parqueo26 = new javax.swing.JLabel();
        parqueo27 = new javax.swing.JLabel();
        parqueo28 = new javax.swing.JLabel();
        parqueo29 = new javax.swing.JLabel();
        parqueo30 = new javax.swing.JLabel();
        estadio = new javax.swing.JLabel();
        parqueo2 = new javax.swing.JLabel();
        parqueo3 = new javax.swing.JLabel();
        parqueo18 = new javax.swing.JLabel();
        fondoparqueo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnListar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parqueo1.setOpaque(true);
        jPanel1.add(parqueo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 30, 20));

        parqueo4.setOpaque(true);
        jPanel1.add(parqueo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 30, 20));

        parqueo5.setOpaque(true);
        jPanel1.add(parqueo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 30, 20));

        parqueo6.setOpaque(true);
        jPanel1.add(parqueo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 30, 20));

        parqueo7.setOpaque(true);
        jPanel1.add(parqueo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 30, 20));

        parqueo8.setOpaque(true);
        jPanel1.add(parqueo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 30, 20));

        parqueo9.setOpaque(true);
        jPanel1.add(parqueo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 20, 30));

        parqueo10.setOpaque(true);
        jPanel1.add(parqueo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 20, 30));

        parqueo11.setOpaque(true);
        jPanel1.add(parqueo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 20, 30));

        parqueo12.setOpaque(true);
        jPanel1.add(parqueo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 20, 30));

        parqueo13.setOpaque(true);
        jPanel1.add(parqueo13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 20, 30));

        parqueo14.setOpaque(true);
        jPanel1.add(parqueo14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 20, 30));

        parqueo15.setOpaque(true);
        jPanel1.add(parqueo15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 20, 30));

        parqueo16.setOpaque(true);
        jPanel1.add(parqueo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 20, 30));

        parqueo17.setOpaque(true);
        jPanel1.add(parqueo17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 20, 30));

        btnvolver.setText("Volver...");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 90, 30));

        parqueo19.setOpaque(true);
        jPanel1.add(parqueo19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 30, 20));

        parqueo20.setOpaque(true);
        jPanel1.add(parqueo20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 30, 20));

        parqueo21.setOpaque(true);
        jPanel1.add(parqueo21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 30, 20));

        parqueo22.setOpaque(true);
        jPanel1.add(parqueo22, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 30, 20));

        parqueo23.setOpaque(true);
        jPanel1.add(parqueo23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 30, 20));

        parqueo24.setOpaque(true);
        jPanel1.add(parqueo24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 30, 20));

        parqueo25.setOpaque(true);
        jPanel1.add(parqueo25, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 30, 20));

        parqueo45.setOpaque(true);
        jPanel1.add(parqueo45, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 30, 20));

        parqueo44.setOpaque(true);
        jPanel1.add(parqueo44, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 30, 20));

        parqueo43.setOpaque(true);
        jPanel1.add(parqueo43, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 30, 20));

        parqueo42.setOpaque(true);
        jPanel1.add(parqueo42, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 30, 20));

        parqueo41.setOpaque(true);
        jPanel1.add(parqueo41, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 30, 20));

        parqueo36.setOpaque(true);
        jPanel1.add(parqueo36, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 30, 20));

        parqueo37.setOpaque(true);
        jPanel1.add(parqueo37, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 30, 20));

        parqueo38.setOpaque(true);
        jPanel1.add(parqueo38, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 30, 20));

        parqueo39.setOpaque(true);
        jPanel1.add(parqueo39, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 30, 20));

        parqueo40.setOpaque(true);
        jPanel1.add(parqueo40, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 30, 20));

        parqueo35.setOpaque(true);
        jPanel1.add(parqueo35, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 30, 20));

        parqueo34.setOpaque(true);
        jPanel1.add(parqueo34, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 30, 20));

        parqueo33.setOpaque(true);
        jPanel1.add(parqueo33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 30, 20));

        parqueo32.setOpaque(true);
        jPanel1.add(parqueo32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 30, 20));

        parqueo31.setOpaque(true);
        jPanel1.add(parqueo31, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 30, 20));

        parqueo26.setOpaque(true);
        jPanel1.add(parqueo26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 30, 20));

        parqueo27.setOpaque(true);
        jPanel1.add(parqueo27, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 30, 20));

        parqueo28.setOpaque(true);
        jPanel1.add(parqueo28, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 30, 20));

        parqueo29.setOpaque(true);
        jPanel1.add(parqueo29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 30, 20));

        parqueo30.setOpaque(true);
        jPanel1.add(parqueo30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 30, 20));
        jPanel1.add(estadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 200, 90));

        parqueo2.setOpaque(true);
        jPanel1.add(parqueo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 30, 20));

        parqueo3.setOpaque(true);
        jPanel1.add(parqueo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 30, 20));

        parqueo18.setOpaque(true);
        jPanel1.add(parqueo18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 20, 30));
        jPanel1.add(fondoparqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 320));

        jTabbedPane1.addTab("Parqueadero", jPanel1);

        jTable1.setModel(TablaDisponible);
        jScrollPane1.setViewportView(jTable1);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vehiculos ingresados", jPanel2);

        jTable2.setModel(TablaHistorial);
        jScrollPane2.setViewportView(jTable2);

        btnListar2.setText("Listar");
        btnListar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListar2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListar2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Historial", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        TablaDisponible.getDataVector().clear();
        for (int i = 1; i < 46; i++) {
            Object[] row = new Object[2];
            row[0]=i;
            for(vehiculo v : obj.vehiculos){
                if(v.getPuesto()==i){
                    row[1]=v.getPlaca();
                    break;
                }else{
                    row[1]="Disponible";
                }
            }
            TablaDisponible.addRow(row);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnListar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar2ActionPerformed
        TablaHistorial.getDataVector().clear();
        for(vehiculo v : obj.vehiculos){
            Object[] row = new Object[4];
            row[0]=v.getPlaca();
            row[1]=v.getFecha();
            row[2]=v.getFHoraingreso();
            row[3]=v.getFHorasalida();
            TablaHistorial.addRow(row);
        }
    }//GEN-LAST:event_btnListar2ActionPerformed

    public Icon escala(String s, int ancho, int altura){
        ImageIcon icono = new ImageIcon(getClass().getResource(s));
        Image imagen = icono.getImage();
        Image imagen2 = imagen.getScaledInstance(ancho, altura, java.awt.Image.SCALE_SMOOTH);
        ImageIcon nuevoicono = new ImageIcon(imagen2);
        return(nuevoicono);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListar2;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel estadio;
    private javax.swing.JLabel fondoparqueo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel parqueo1;
    private javax.swing.JLabel parqueo10;
    private javax.swing.JLabel parqueo11;
    private javax.swing.JLabel parqueo12;
    private javax.swing.JLabel parqueo13;
    private javax.swing.JLabel parqueo14;
    private javax.swing.JLabel parqueo15;
    private javax.swing.JLabel parqueo16;
    private javax.swing.JLabel parqueo17;
    private javax.swing.JLabel parqueo18;
    private javax.swing.JLabel parqueo19;
    private javax.swing.JLabel parqueo2;
    private javax.swing.JLabel parqueo20;
    private javax.swing.JLabel parqueo21;
    private javax.swing.JLabel parqueo22;
    private javax.swing.JLabel parqueo23;
    private javax.swing.JLabel parqueo24;
    private javax.swing.JLabel parqueo25;
    private javax.swing.JLabel parqueo26;
    private javax.swing.JLabel parqueo27;
    private javax.swing.JLabel parqueo28;
    private javax.swing.JLabel parqueo29;
    private javax.swing.JLabel parqueo3;
    private javax.swing.JLabel parqueo30;
    private javax.swing.JLabel parqueo31;
    private javax.swing.JLabel parqueo32;
    private javax.swing.JLabel parqueo33;
    private javax.swing.JLabel parqueo34;
    private javax.swing.JLabel parqueo35;
    private javax.swing.JLabel parqueo36;
    private javax.swing.JLabel parqueo37;
    private javax.swing.JLabel parqueo38;
    private javax.swing.JLabel parqueo39;
    private javax.swing.JLabel parqueo4;
    private javax.swing.JLabel parqueo40;
    private javax.swing.JLabel parqueo41;
    private javax.swing.JLabel parqueo42;
    private javax.swing.JLabel parqueo43;
    private javax.swing.JLabel parqueo44;
    private javax.swing.JLabel parqueo45;
    private javax.swing.JLabel parqueo5;
    private javax.swing.JLabel parqueo6;
    private javax.swing.JLabel parqueo7;
    private javax.swing.JLabel parqueo8;
    private javax.swing.JLabel parqueo9;
    // End of variables declaration//GEN-END:variables
}
